### ISSUE TITLE
Report "< .001" when p is lower than 0.001; otherwise report actual p value

### ISSUE THREAD

**Issue by jolyphil** [benjann/estout#32]
Thanks for this great package that has made my work much easier over the last years!

I am trying to reproduce an APA table. See Table 3: 
https://apastyle.apa.org/style-grammar-guidelines/tables-figures/sample-tables#regression 

I roughly get what I want with the following commands:

```
sysuse auto, clear
reg price weight length
estout, cells("b(label(Estimate)) se(label(SE)) ci(label(95% CI) par([ , ])) p")
```
The only thing I am missing is a way to dynamically convert a p value under 0.001 with "< .001". If the the p value is over 0.001, the actual value should be reported. 

Is there a way to do this with estout? 

Many thanks!

**Comment by benjann** [comment]
I do not have a very elegant solution for you but here's a trick using substitute():

***
sysuse auto, clear
reg price weight length
estout, cells("b p(par(p=) f(3))") substitute("p=.000" " <.001""p=" "  ") nolz
***

The result is not necessarily entirely correct, because values lower than .001 that are rounded up to .001 are displayed as .001 and not as <.001.

So you would also do something like the following:

***
sysuse auto, clear

reg price weight length
mat pval = r(table)
mat pval = pval["pvalue",1...]
forv i = 1 / `=colsof(pval)' {
    if (pval[1,`i']<.001) mat pval[1,`i'] = .a
}
estadd matrix pval

estout, cells("b pval(f(3))") substitute("   .a" "<.001") nolz
***

ben

**Comment by NilsEnevoldsen** [comment]
@benjann I think it would be appropriate to close this issue.

**Comment by fredericky123** [comment]
If in the correlation table, we can set such notes, that will be great.
All correlations with absolute values above 0.050 have p-values below 0.010

This is the requirement from APA
